### PR TITLE
Avoid passing null to rawurlencode()

### LINKED ISSUE #12: rawurlencode(): Passing null to parameter #1 is deprecated
A couple of deprecation warnings with PHP 8.3:

> Deprecated: rawurlencode(): Passing null to parameter 1 ($string) of type string is deprecated in carlos-mg89/oauth/src/OAuth/OAuth1/Signature/Signature.php on line 57

> Deprecated: rawurlencode(): Passing null to parameter 1 ($string) of type string is deprecated in carlos-mg89/oauth/src/OAuth/OAuth1/Service/AbstractService.php on line 225

### PR DESCRIPTION
**Pull request by samwilson**
Passing null to rawurlencode() is now deprecated, so this coalescese null to the empty string.

Fixes #12

### CODE REVIEW

**Comment by tacman** [comment]
@carlos-mg89 can you approve this PR please, and I'll close #13 .

**Review by carlos-mg89 — APPROVED** [review]

**Review by carlos-mg89 — CHANGES_REQUESTED** [review]
Could you please review latest #15 ? It's been merged. The PRs now look messy to me.
And I don't have time to review them all.

You could just close all PRs that aren't final. Or is this the final one?

If you fix the conflicts, I'll make sure this one goes live and release a new version of the library.

**Comment by tacman** [comment]
@samwilson can you make sure this PR works with your library as expected?  I don't use it directly, only through phpFlickr.  Thx.

**Comment by samwilson** [comment]
> If you fix the conflicts, I'll make sure this one goes live and release a new version of the library.

I've brought this up to date with current master.

I'm not 100% sure that there aren't other similar situations, but I've not hit them in general usage yet to won't add fixes for them yet. :-)

**Comment by samwilson** [comment]
I think this is ready for review now.

**Review by carlos-mg89 — APPROVED** [review]

**Comment by carlos-mg89** [comment]
> I think this is ready for review now.

PR approved and new release launched.

Thanks for helping!

**Pull request merged**
